<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Apmasuk_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get apmasuk by sn
     */
    function get_apmasuk($sn)
    {
        return $this->db->get_where('tb_apmasuk',array('serial_number'=>$sn))->row_array();
    }

    /*
     * Get all apmasuk
     */
    function getall_apmasuk()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tb_apmasuk')->result_array();
    }

    /*
     * function to add new apmasuk
     */
    function add_apmasuk($params)
    {
        $this->db->insert('tb_apmasuk',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update apmasuk
     */
    function update_apmasuk($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tb_apmasuk',$params);
    }

    /*
     * function to delete apmasuk
     */
    function delete_apmasuk($id)
    {
        $this->db->delete('tb_apmasuk',array('id' => $id));
    }
}
