<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Apmasuk_model extends CI_Model
{

    private $_table = "tb_apmasuk";

    /*
     * Get apmasuk by sn
     */
    function get_apmasuk($id)
    {
        return $this->db->get_where($this->_table,array('id'=>$id))->row_array();
    }

    /*
     * Get all apmasuk
     */
    function getall_apmasuk()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get($this->_table)->result_array();
    }

    /*
     * function to add new apmasuk
     */
    function add_apmasuk($params)
    {
        $this->db->insert($this->_table,$params);
        return $this->db->insert_id();
    }

    /*
     * function to update apmasuk
     */
    function update_apmasuk($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update($this->_table,$params);
    }

    /*
     * function to delete apmasuk
     */
    function delete_apmasuk($id)
    {
        return $this->db->delete($this->_table,array('id' => $id));
    }
}
